controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints: [shoulder_joint, elbow_joint]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 1.0
      shoulder_joint: {trajectory: 0.075, goal: 0.02}
      elbow_joint: {trajectory: 0.075, goal: 0.02}

gripper_controller:
  ros__parameters:
    joints: [left_finger_joint, right_finger_joint]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints:
      goal_time: 1.0
      left_finger_joint: {trajectory: 0.01, goal: 0.003}
      right_finger_joint: {trajectory: 0.01, goal: 0.003}
